### ISSUE TITLE
API 的请求数据格式有问题

### ISSUE THREAD

**Issue by zzseki** [PGRjoystick/rvc-fastapi#1]
您好，请问我这是哪里不对吗：
![屏幕截图 2024-09-21 105354](https://github.com/user-attachments/assets/da5189e1-82a6-435c-9ca5-552470976574)
![屏幕截图 2024-09-21 105459](https://github.com/user-attachments/assets/349ca4c0-abb6-4a25-a95d-dea908f4f79e)

**Comment by PGRjoystick** [comment]
hello, sorry for the late reply

this repo were meant to be used alongside with [RVC-Project](https://github.com/fumiama/Retrieval-based-Voice-Conversion-WebUI). you need to setup the RVC-project and then put this file in the project directory and run that inside the venv

if you have any question, feel free to ask with plain english. i don't understand chinese, sorry...
